# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AuthService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x41uthService.proto\x12\x0b\x41uthService\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"&\n\x0eLotteryRequest\x12\x14\n\x0crandomNumber\x18\x01 \x01(\x05\"#\n\x0fLotteryResponse\x12\x10\n\x08response\x18\x01 \x01(\t2\xe7\x01\n\x0b\x41uthService\x12@\n\x08SayHello\x12\x19.AuthService.HelloRequest\x1a\x17.AuthService.HelloReply\"\x00\x12\x45\n\rSayHelloAgain\x12\x19.AuthService.HelloRequest\x1a\x17.AuthService.HelloReply\"\x00\x12O\n\x10LotteryGenerator\x12\x1b.AuthService.LotteryRequest\x1a\x1c.AuthService.LotteryResponse\"\x00\x42\x38\n\x1cio.grpc.examples.AuthServiceB\x10\x41uthServiceProtoP\x01\xa2\x02\x03HLWb\x06proto3')



_HELLOREQUEST = DESCRIPTOR.message_types_by_name['HelloRequest']
_HELLOREPLY = DESCRIPTOR.message_types_by_name['HelloReply']
_LOTTERYREQUEST = DESCRIPTOR.message_types_by_name['LotteryRequest']
_LOTTERYRESPONSE = DESCRIPTOR.message_types_by_name['LotteryResponse']
HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'AuthService_pb2'
  # @@protoc_insertion_point(class_scope:AuthService.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREPLY,
  '__module__' : 'AuthService_pb2'
  # @@protoc_insertion_point(class_scope:AuthService.HelloReply)
  })
_sym_db.RegisterMessage(HelloReply)

LotteryRequest = _reflection.GeneratedProtocolMessageType('LotteryRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOTTERYREQUEST,
  '__module__' : 'AuthService_pb2'
  # @@protoc_insertion_point(class_scope:AuthService.LotteryRequest)
  })
_sym_db.RegisterMessage(LotteryRequest)

LotteryResponse = _reflection.GeneratedProtocolMessageType('LotteryResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOTTERYRESPONSE,
  '__module__' : 'AuthService_pb2'
  # @@protoc_insertion_point(class_scope:AuthService.LotteryResponse)
  })
_sym_db.RegisterMessage(LotteryResponse)

_AUTHSERVICE = DESCRIPTOR.services_by_name['AuthService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\034io.grpc.examples.AuthServiceB\020AuthServiceProtoP\001\242\002\003HLW'
  _HELLOREQUEST._serialized_start=34
  _HELLOREQUEST._serialized_end=62
  _HELLOREPLY._serialized_start=64
  _HELLOREPLY._serialized_end=93
  _LOTTERYREQUEST._serialized_start=95
  _LOTTERYREQUEST._serialized_end=133
  _LOTTERYRESPONSE._serialized_start=135
  _LOTTERYRESPONSE._serialized_end=170
  _AUTHSERVICE._serialized_start=173
  _AUTHSERVICE._serialized_end=404
# @@protoc_insertion_point(module_scope)
