# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import AuthService_pb2 as AuthService__pb2


class AuthServiceStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/AuthService.AuthService/SayHello',
                request_serializer=AuthService__pb2.HelloRequest.SerializeToString,
                response_deserializer=AuthService__pb2.HelloReply.FromString,
                )
        self.SayHelloAgain = channel.unary_unary(
                '/AuthService.AuthService/SayHelloAgain',
                request_serializer=AuthService__pb2.HelloRequest.SerializeToString,
                response_deserializer=AuthService__pb2.HelloReply.FromString,
                )
        self.LotteryGenerator = channel.unary_unary(
                '/AuthService.AuthService/LotteryGenerator',
                request_serializer=AuthService__pb2.LotteryRequest.SerializeToString,
                response_deserializer=AuthService__pb2.LotteryResponse.FromString,
                )


class AuthServiceServicer(object):
    """The greeting service definition.
    """

    def SayHello(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SayHelloAgain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LotteryGenerator(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=AuthService__pb2.HelloRequest.FromString,
                    response_serializer=AuthService__pb2.HelloReply.SerializeToString,
            ),
            'SayHelloAgain': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHelloAgain,
                    request_deserializer=AuthService__pb2.HelloRequest.FromString,
                    response_serializer=AuthService__pb2.HelloReply.SerializeToString,
            ),
            'LotteryGenerator': grpc.unary_unary_rpc_method_handler(
                    servicer.LotteryGenerator,
                    request_deserializer=AuthService__pb2.LotteryRequest.FromString,
                    response_serializer=AuthService__pb2.LotteryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AuthService.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """The greeting service definition.
    """

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AuthService.AuthService/SayHello',
            AuthService__pb2.HelloRequest.SerializeToString,
            AuthService__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SayHelloAgain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AuthService.AuthService/SayHelloAgain',
            AuthService__pb2.HelloRequest.SerializeToString,
            AuthService__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LotteryGenerator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AuthService.AuthService/LotteryGenerator',
            AuthService__pb2.LotteryRequest.SerializeToString,
            AuthService__pb2.LotteryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
