# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RecordService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13RecordService.proto\x12\rRecordService\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"&\n\x0eLotteryRequest\x12\x14\n\x0crandomNumber\x18\x01 \x01(\x05\"#\n\x0fLotteryResponse\x12\x10\n\x08response\x18\x01 \x01(\t2\xa0\x01\n\rRecordService\x12\x44\n\x08SayHello\x12\x1b.RecordService.HelloRequest\x1a\x19.RecordService.HelloReply\"\x00\x12I\n\rSayHelloAgain\x12\x1b.RecordService.HelloRequest\x1a\x19.RecordService.HelloReply\"\x00\x42<\n\x1eio.grpc.examples.RecordServiceB\x12RecordServiceProtoP\x01\xa2\x02\x03HLWb\x06proto3')



_HELLOREQUEST = DESCRIPTOR.message_types_by_name['HelloRequest']
_HELLOREPLY = DESCRIPTOR.message_types_by_name['HelloReply']
_LOTTERYREQUEST = DESCRIPTOR.message_types_by_name['LotteryRequest']
_LOTTERYRESPONSE = DESCRIPTOR.message_types_by_name['LotteryResponse']
HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'RecordService_pb2'
  # @@protoc_insertion_point(class_scope:RecordService.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREPLY,
  '__module__' : 'RecordService_pb2'
  # @@protoc_insertion_point(class_scope:RecordService.HelloReply)
  })
_sym_db.RegisterMessage(HelloReply)

LotteryRequest = _reflection.GeneratedProtocolMessageType('LotteryRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOTTERYREQUEST,
  '__module__' : 'RecordService_pb2'
  # @@protoc_insertion_point(class_scope:RecordService.LotteryRequest)
  })
_sym_db.RegisterMessage(LotteryRequest)

LotteryResponse = _reflection.GeneratedProtocolMessageType('LotteryResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOTTERYRESPONSE,
  '__module__' : 'RecordService_pb2'
  # @@protoc_insertion_point(class_scope:RecordService.LotteryResponse)
  })
_sym_db.RegisterMessage(LotteryResponse)

_RECORDSERVICE = DESCRIPTOR.services_by_name['RecordService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\036io.grpc.examples.RecordServiceB\022RecordServiceProtoP\001\242\002\003HLW'
  _HELLOREQUEST._serialized_start=38
  _HELLOREQUEST._serialized_end=66
  _HELLOREPLY._serialized_start=68
  _HELLOREPLY._serialized_end=97
  _LOTTERYREQUEST._serialized_start=99
  _LOTTERYREQUEST._serialized_end=137
  _LOTTERYRESPONSE._serialized_start=139
  _LOTTERYRESPONSE._serialized_end=174
  _RECORDSERVICE._serialized_start=177
  _RECORDSERVICE._serialized_end=337
# @@protoc_insertion_point(module_scope)
