# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import staff_pb2 as staff__pb2


class StaffManagerStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddDoctor = channel.unary_unary(
                '/staff.StaffManager/AddDoctor',
                request_serializer=staff__pb2.AddDoc.SerializeToString,
                response_deserializer=staff__pb2.AddDocReply.FromString,
                )


class StaffManagerServicer(object):
    """The greeting service definition.
    """

    def AddDoctor(self, request, context):
        """manage staff
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StaffManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddDoctor': grpc.unary_unary_rpc_method_handler(
                    servicer.AddDoctor,
                    request_deserializer=staff__pb2.AddDoc.FromString,
                    response_serializer=staff__pb2.AddDocReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'staff.StaffManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StaffManager(object):
    """The greeting service definition.
    """

    @staticmethod
    def AddDoctor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/staff.StaffManager/AddDoctor',
            staff__pb2.AddDoc.SerializeToString,
            staff__pb2.AddDocReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
