# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StaffManager.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12StaffManager.proto\x12\nhelloworld\"&\n\x0eLotteryRequest\x12\x14\n\x0crandomNumber\x18\x01 \x01(\x05\"#\n\x0fLotteryResponse\x12\x10\n\x08response\x18\x01 \x01(\t\"z\n\rDoctorDetials\x12\x10\n\x08\x44octorID\x18\x01 \x01(\t\x12\x10\n\x08Password\x18\x02 \x01(\t\x12\x15\n\rQualification\x18\x03 \x01(\t\x12\x0e\n\x06\x44\x65ptID\x18\x04 \x01(\x05\x12\x0c\n\x04\x46\x65\x65s\x18\x05 \x01(\x05\x12\x10\n\x08JobTitle\x18\x06 \x01(\t\"!\n\x0eStorageReponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xad\x01\n\x0fStaffManagement\x12M\n\x10LotteryGenerator\x12\x1a.helloworld.LotteryRequest\x1a\x1b.helloworld.LotteryResponse\"\x00\x12K\n\x10\x61\x64\x64\x44octorProfile\x12\x19.helloworld.DoctorDetials\x1a\x1a.helloworld.StorageReponse\"\x00\x42\x36\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3')



_LOTTERYREQUEST = DESCRIPTOR.message_types_by_name['LotteryRequest']
_LOTTERYRESPONSE = DESCRIPTOR.message_types_by_name['LotteryResponse']
_DOCTORDETIALS = DESCRIPTOR.message_types_by_name['DoctorDetials']
_STORAGEREPONSE = DESCRIPTOR.message_types_by_name['StorageReponse']
LotteryRequest = _reflection.GeneratedProtocolMessageType('LotteryRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOTTERYREQUEST,
  '__module__' : 'StaffManager_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.LotteryRequest)
  })
_sym_db.RegisterMessage(LotteryRequest)

LotteryResponse = _reflection.GeneratedProtocolMessageType('LotteryResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOTTERYRESPONSE,
  '__module__' : 'StaffManager_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.LotteryResponse)
  })
_sym_db.RegisterMessage(LotteryResponse)

DoctorDetials = _reflection.GeneratedProtocolMessageType('DoctorDetials', (_message.Message,), {
  'DESCRIPTOR' : _DOCTORDETIALS,
  '__module__' : 'StaffManager_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.DoctorDetials)
  })
_sym_db.RegisterMessage(DoctorDetials)

StorageReponse = _reflection.GeneratedProtocolMessageType('StorageReponse', (_message.Message,), {
  'DESCRIPTOR' : _STORAGEREPONSE,
  '__module__' : 'StaffManager_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.StorageReponse)
  })
_sym_db.RegisterMessage(StorageReponse)

_STAFFMANAGEMENT = DESCRIPTOR.services_by_name['StaffManagement']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001\242\002\003HLW'
  _LOTTERYREQUEST._serialized_start=34
  _LOTTERYREQUEST._serialized_end=72
  _LOTTERYRESPONSE._serialized_start=74
  _LOTTERYRESPONSE._serialized_end=109
  _DOCTORDETIALS._serialized_start=111
  _DOCTORDETIALS._serialized_end=233
  _STORAGEREPONSE._serialized_start=235
  _STORAGEREPONSE._serialized_end=268
  _STAFFMANAGEMENT._serialized_start=271
  _STAFFMANAGEMENT._serialized_end=444
# @@protoc_insertion_point(module_scope)
