# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import StaffManager_pb2 as StaffManager__pb2


class StaffManagementStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LotteryGenerator = channel.unary_unary(
                '/helloworld.StaffManagement/LotteryGenerator',
                request_serializer=StaffManager__pb2.LotteryRequest.SerializeToString,
                response_deserializer=StaffManager__pb2.LotteryResponse.FromString,
                )
        self.addDoctorProfile = channel.unary_unary(
                '/helloworld.StaffManagement/addDoctorProfile',
                request_serializer=StaffManager__pb2.DoctorDetials.SerializeToString,
                response_deserializer=StaffManager__pb2.StorageReponse.FromString,
                )


class StaffManagementServicer(object):
    """The greeting service definition.
    """

    def LotteryGenerator(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def addDoctorProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StaffManagementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LotteryGenerator': grpc.unary_unary_rpc_method_handler(
                    servicer.LotteryGenerator,
                    request_deserializer=StaffManager__pb2.LotteryRequest.FromString,
                    response_serializer=StaffManager__pb2.LotteryResponse.SerializeToString,
            ),
            'addDoctorProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.addDoctorProfile,
                    request_deserializer=StaffManager__pb2.DoctorDetials.FromString,
                    response_serializer=StaffManager__pb2.StorageReponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'helloworld.StaffManagement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StaffManagement(object):
    """The greeting service definition.
    """

    @staticmethod
    def LotteryGenerator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/helloworld.StaffManagement/LotteryGenerator',
            StaffManager__pb2.LotteryRequest.SerializeToString,
            StaffManager__pb2.LotteryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def addDoctorProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/helloworld.StaffManagement/addDoctorProfile',
            StaffManager__pb2.DoctorDetials.SerializeToString,
            StaffManager__pb2.StorageReponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
